# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/configuration/#theme-parameters

colorScheme = "okami"
defaultAppearance = "light"          # valid options: light or dark
autoSwitchAppearance = true
footer.showAppearanceSwitcher = true
footer.showThemeAttribution = false

enableSearch = true
enableCodeCopy = true

mainSections = ["posts"]
# robots = ""
footer.showScrollToTop = true

[homepage]
layout = "profile" # valid options: page, profile, custom
showRecent = true

[article]
showDate = true
showDateUpdated = false
showAuthor = true
showBreadcrumbs = false
showDraftLabel = true
showEdit = false
editAppendPath = true
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = true
showTaxonomies = false
showWordCount = false
showComments = true
sharingLinks = ["twitter", "reddit", "linkedin"]

[list]
showBreadcrumbs = true
showSummary = false
showTableOfContents = true
groupByYear = false

[taxonomy]
showTermCount = true

[sitemap]
excludedKinds = ["taxonomy", "term"]

[fathomAnalytics]
# site = "ABC12345"
# domain = "llama.yoursite.com"

[verification]
# google = ""
# bing = ""
# pinterest = ""
# yandex = ""

[author]
name = "Adrien Beaudouin"
image = "author.jpg"
bio = "A senior web developer @janze"
links = [
    { email = "mailto:adrien@okami101.io" },
    { github = "https://github.com/adr1enbe4udou1n" },
    { linkedin = "https://linkedin.com/in/adr1enbe4udou1n" },
    { bluesky = "https://bsky.app/profile/adr1enbe4udou1n.bsky.social" },
]
