steps:
  - name: restore-cache
    image: meltwater/drone-cache
    volumes:
      - woodpecker-cache:/woodpecker/src/resources
    when:
      event: push
    settings:
      mount:
        - woodpecker-cache

  - name: build
    image: hugomods/hugo:latest
    commands:
      - hugo --minify
    volumes:
      - woodpecker-cache:/woodpecker/src/resources
    when:
      event: push
    backend_options:
      kubernetes:
        tolerations:
          - key: node-role.kubernetes.io/runner
            operator: Exists
        nodeSelector:
          node-role.kubernetes.io/runner: "true"

  - name: rebuild-cache
    image: meltwater/drone-cache
    volumes:
      - woodpecker-cache:/woodpecker/src/resources
    when:
      event: push
    settings:
      mount:
        - woodpecker-cache

  - name: publish
    image: woodpeckerci/plugin-docker-buildx
    when:
      event: push
    settings:
      repo: gitea.okami101.io/adr1enbe4udou1n/blog
      registry: https://gitea.okami101.io
      username: woodpecker
      password:
        from_secret: gitea_password
