steps:
  - name: build
    image: hugomods/hugo:latest
    commands:
      - hugo --minify
    when:
      branch: main
    backend_options:
      kubernetes:
        tolerations:
          - key: node-role.kubernetes.io/runner
            operator: Exists
        nodeSelector:
          node-role.kubernetes.io/runner: "true"

  - name: publish
    image: woodpeckerci/plugin-docker-buildx
    when:
      branch: main
    settings:
      repo: gitea.okami101.io/adr1enbe4udou1n/blog
      registry: https://gitea.okami101.io
      username: woodpecker
      password:
        from_secret: gitea_password
