on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/cache@v4
        with:
          path: resources
          key: ${{ runner.os }}-resources
      - uses: peaceiris/actions-hugo@v3
        with:
          extended: true
      - name: Build
        run: hugo --minify
      - uses: https://gitea.okami101.io/okami101/actions/docker@main
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
