on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: peaceiris/actions-hugo@v3
        with:
          extended: true
      - uses: actions/cache@v4
        with:
          path: resources
          key: ${{ runner.os }}-resources
      - name: Build
        run: hugo --minify
      - uses: docker/login-action@v3
        with:
          registry: ${{ vars.CONTAINER_REGISTRY_URL }}
          username: ${{ vars.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
      - name: List files in the repository
        run: |
          ls public
      # - uses: docker/build-push-action@v6
      #   with:
      #     push: true
      #     tags: ${{ vars.CONTAINER_REGISTRY_URL }}/${{ gitea.repository }}:latest
