on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: peaceiris/actions-hugo@v3
        with:
          extended: true
      - uses: actions/cache@v4
        with:
          path: resources
          key: ${{ runner.os }}-resources
      - name: Build test
        run: hugo --minify
      - uses: https://gitea.okami101.io/okami101/docker-action@main
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          username: ${{ vars.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
