on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/cache@v4
        with:
          path: resources
          key: ${{ runner.os }}-resources
      - uses: peaceiris/actions-hugo@v3
        with:
          extended: true
      - name: Build test
        run: hugo --minify
      - uses: https://gitea.okami101.io/okami101/actions/docker@main
        with:
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
          gitea-token: ${{ secrets.RELEASE_TOKEN }}
