on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: peaceiris/actions-hugo@v3
        with:
          extended: true
      - uses: actions/cache@v4
        with:
          path: resources
          key: ${{ runner.os }}-resources
      - name: Build
        run: hugo --minify
      - uses: docker/metadata-action@v5
        if: gitea.event_name == 'tag'
        id: meta
        with:
          images: ${{ vars.CONTAINER_REGISTRY_URL }}/${{ gitea.repository }}
      - uses: docker/login-action@v3
        if: gitea.event_name == 'tag'
        with:
          registry: ${{ vars.CONTAINER_REGISTRY_URL }}
          username: ${{ vars.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
      - uses: docker/build-push-action@v6
        if: gitea.event_name == 'tag'
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
