on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !startsWith(gitea.ref, 'refs/tags/v') }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/cache@v4
        with:
          path: resources
          key: ${{ runner.os }}-resources
      - uses: peaceiris/actions-hugo@v3
        with:
          extended: true
      - name: Build
        run: hugo --minify
      - uses: https://gitea.okami101.io/okami101/actions/docker@main
        with:
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

  deploy:
    uses: gitea.okami101.io/okami101/actions/.gitea/workflows/release.yaml@main
    secrets:
      password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
