on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: peaceiris/actions-hugo@v3
        with:
          extended: true
      - uses: actions/cache@v4
        with:
          path: resources
          key: ${{ runner.os }}-resources
      - name: Build
        run: hugo --minify
      - uses: https://gitea.okami101.io/okami101/docker-action/.gitea/workflows/push-image@d2f8e211e13fbccfa7cc15efeeb4175bd7015027
        #if: startsWith(github.ref, 'refs/tags/v')
